MODULE PARAMS
IMPLICIT NONE

!--MODEL PARAMETERS--!
INTEGER, PARAMETER		:: N = 300
INTEGER, PARAMETER		:: K = 3
INTEGER, PARAMETER		:: R = 2
INTEGER, PARAMETER		:: S = 2
INTEGER, PARAMETER		:: Q = 2
INTEGER, PARAMETER		:: P = 2

!--STRINGS FORMAT--!
CHARACTER(LEN=80)		:: LINE		
CHARACTER(LEN=13), PARAMETER	:: datetime_fmt = '%Y%m%d %H%M%S'

END MODULE PARAMS
